[project]
name = "dopy"
version = "0.3.0"
description = "To-Do list on Command Line Interface"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Bruno Rocha", email = "rochacbruno@gmail.com"}
]
keywords = ["todo", "cli", "task", "productivity"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities",
]

dependencies = [
    "termcolor>=2.0.0",
    "docopt>=0.6.2",
]

[project.urls]
Homepage = "https://github.com/rochacbruno/dopy"
Repository = "https://github.com/rochacbruno/dopy"
Issues = "https://github.com/rochacbruno/dopy/issues"

[project.scripts]
dopy = "dopy.do:main_entry"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dopy"]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
]
